"""add user profile fields (avatar, department, location, bio, dob)

Revision ID: 2cb76f30550a
Revises: e833b45cc876
Create Date: 2026-07-24 17:24:40.245279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb76f30550a'
down_revision = 'e833b45cc876'
branch_labels = None
depends_on = None


def upgrade():
    # Idempotent. The baseline migration now builds users instead of leaving
    # it to a schema created by hand, so on a database restored from nothing
    # this column already exists by the time we get here and there is nothing
    # to add. On the production database this migration ran long ago. Either
    # way, re-running it must not raise - which is what it did before, because
    # a batch_alter_table block cannot guard its own statements.
    _bind = op.get_bind()
    _inspector = sa.inspect(_bind)
    if "users" not in set(_inspector.get_table_names()):
        return
    if "avatar_key" in {c["name"] for c in _inspector.get_columns("users")}:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('bio')
        batch_op.drop_column('location')
        batch_op.drop_column('department')
        batch_op.drop_column('avatar_key')

    # ### end Alembic commands ###
