"""add on_hold and void status fields

Revision ID: 7ae8edf352c4
Revises: 4dcdb36dfe98
Create Date: 2026-07-21 22:28:20.638187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae8edf352c4'
down_revision = '4dcdb36dfe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_hold_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hold_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('held_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('held_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('voided_by_id', sa.Integer(), nullable=True))
        # void_seconds already exists as NOT NULL DEFAULT 0; left as is.
        batch_op.create_foreign_key(None, 'users', ['held_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['voided_by_id'], ['id'])

    # ### end Alembic commands ###

    # Backfill the new counter so it behaves like the existing ones.
    op.execute("UPDATE tasks SET on_hold_seconds = 0 WHERE on_hold_seconds IS NULL")

    # "Hold" was a half-wired status: present in the calendar filter and
    # two dashboard charts, but missing from the board, the edit form and
    # the time accumulator, so tasks parked there lost their elapsed time.
    # It is superseded by the real "On Hold" status.
    op.execute("UPDATE tasks SET status = 'On Hold' WHERE status = 'Hold'")

    # The model has always defaulted to "Pending" while the UI only ever
    # used "Assigned"; any row still carrying it would not match a board
    # column and would silently vanish from the kanban.
    op.execute("UPDATE tasks SET status = 'Assigned' WHERE status = 'Pending'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('voided_by_id')
        batch_op.drop_column('voided_at')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('held_by_id')
        batch_op.drop_column('held_at')
        batch_op.drop_column('hold_reason')
        batch_op.drop_column('on_hold_seconds')

    # ### end Alembic commands ###
