"""add thumbnail columns to task_files

Revision ID: e833b45cc876
Revises: 7ae8edf352c4
Create Date: 2026-07-22 23:01:20.060149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e833b45cc876'
down_revision = '7ae8edf352c4'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_key', sa.String(length=1000), nullable=True))

        # server_default is required, not cosmetic: the table already
        # has rows, and adding a NOT NULL column without one fails
        # outright on PostgreSQL. Every existing file correctly starts
        # as "pending" - none of them has a thumbnail yet.
        batch_op.add_column(sa.Column(
            'thumbnail_state',
            sa.String(length=16),
            nullable=False,
            server_default='pending',
        ))

        batch_op.create_index(
            batch_op.f('ix_task_files_thumbnail_state'),
            ['thumbnail_state'],
            unique=False,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_files_thumbnail_state'))
        batch_op.drop_column('thumbnail_state')
        batch_op.drop_column('thumbnail_key')

    # ### end Alembic commands ###
